/*
 * global_cfg.h
 *
 *  Created on: March 9th, 2017
 *      Author: Steven Hall
 *
 */

#ifndef GLOBAL_CFG_H
#define GLOBAL_CFG_H

// Configuration Options

// **************************
// Auto generated by script *
// **************************
// This definition is generated by ../../add_timestamp_to_config.c which is
// setup to build and run automatically before the main project builds,
// therefore IF YOU CHANGE THE NAME OF THIS DEFINE YOU NEED TO CHANGE THE SEARCH
// STRING IN ../../add_timestamp_to_config.c AS WELL
#define TIMESTAMP_AT_BUILDTIME 1491506399
// ********************
// End auto-generated *
// ********************

// [0] = Beta
// [1] = Alpha
// [2] = NOT USED
// [3] = Gateway
// Specifies the Tag Type being used
#define TAG_TYPE 0

// Specifies the number of retries for send
// Original value: 6
#define RADIO_SEND_MAX_RETRIES 6

// Specifies the number of retries for receive
// Original value: 6
#define RADIO_RECEIVE_MAX_RETRIES 6

// Specifies the timeout for send and receive in milliseconds
// Original value: (500)
#define RADIO_SEND_ACK_TIMEOUT_TIME_MS (500)

// Specifies the timeout for send and receive in milliseconds
// Original value: (500)
#define RADIO_RECEIVE_ACK_TIMEOUT_TIME_MS (500)

// Original value: 3600000000
#define HOUR_SLEEP_TICKS 3600000000
// Original value: 60000000
#define MINUTE_SLEEP_TICKS 60000000

// Original value: 0x7FFF
#define MAX_EEPROM_ADDRESS 0x7FFF
// Original value: 0x0000
#define MIN_EEPROM_ADDRESS 0x0000

// Sample rate in Hz for Accelerometer
// Allowed Values Are:
// 1, 10, 25, 50, 100, 200, 400Hz
// Original value: 10
#define ACCELEROMETER_SAMPLE_RATE_HZ 10

// Sample rate in Hz for Heart Rate Sensor
// Allowed Values Are:
// 50, 100, 167, 200, 400, 600, 800, 1000Hz
// Original value: 100
#define HEARTRATE_SAMPLE_RATE_HZ 100


/* DEBUG FLAGS */

/*** Print the contents of the packets to a file ***/
/* verbose_alphaRadioTest also needs to be set to print packets to file */
static const int print_packet_to_file_alpha = 0;

/* verbose_betaRadioTest also needs to be set to print packets to file */
static const int print_packet_to_file_beta = 0;

/* verbose_gatewayRadioTest also needs to be set to print packets to file */
static const int print_packet_to_file_gateway = 0;



/*** verbose for printing debug messages trough different threads/Functions ***/
static const int verbose_main = 1;

/* sensor blocks */
static const int verbose_sensors = 1;
static const int verbose_i2c = 0;

/* Serialization of sensor packets */
static const int verbose_serialize = 0;

/* EEPROM */
static const int verbose_eeprom = 0;

/* Arduino Communications */
static const int verbose_arduinoCom = 0;

/* Alpha send and receive radio */
static const int verbose_alphaRadio = 1;

/* Tests suites */
static const int verbose_serializeTest    = 0;
static const int verbose_betaRadioTest    = 1;
static const int verbose_alphaRadioTest   = 1;
static const int verbose_gatewayRadioTest = 0;
static const int verbose_arduinoComTest   = 0;
static const int verbose_eepromTest       = 1;

// Timestamp
static const int verbose_timestamp = 0;
static const int verbose_uptime    = 0;

// Sleep output
static const int verbose_sleep = 0;

/*** enable/disable eeprom ***/
static const int usingEeprom = 0;

/*** ignore sensors ***/
static const int ignoreSensors = 0;

#endif // GLOBAL_CFG_H

